### ISSUE TITLE
Поля на планете

### ISSUE THREAD

**Issue by darkzmii** [supernova-ws/SuperNova#14]
При установке количества планет в системе больше чем стандартное, есть большая вероятность получить планету без полей совсем, вследствие того что массив с возможными величинами заполнен только на стандарт и в 60% случаев информация берется из него.

**Comment by kosmosofby** [comment]
Несли хотите получить код браузерки spacerun.ru напишите мне на почту kosmos гав lets.by
Игру писал я сам
