### ISSUE TITLE
Incompatible license

### ISSUE THREAD

**Issue by HiddenKn** [supernova-ws/SuperNova#19]
Hi! I don't really think your license (GNU General Public License) and your additional license terms are compatible. (https://www.gnu.org/licenses/gpl-faq.html#WhatIsCompatible)

* The Gnu General Public License allows you to sell the modified code, as long as you provide the source. (https://www.gnu.org/licenses/gpl-faq.html#GPLCommercially)
* You state that developers should keep intact your copyright notices, while you are using a COPYLEFT license? This WILL confuse people that want to use your software. (1) 

I was hoping to make improvements to this project and share them with the public, but because of these problems, I cannot release them under the GNU General Public License.

(1) The GNU General Public license does state that you should provide a copy of the License on top of every source file (including the authors name), but this is basically the opposite of claiming a copyright on the source file. Which is what I believe is your intention.

**Comment by funtaps** [comment]
GNU GPL пункт 2 говорит о том, что я могу использовать ЛЮБЫЕ куски исходного кода сколь угодно, пока работа на их основе остаётся под GNU GPL (указывает на то, что файлы были изменены, что они под этой лицензией и предупреждает об отсутствии гарантий).
Таким образом, в соответствии с этой лицензией я МОГУ вырезать или изменить ЛЮБЫЕ куски проекта, включая "any copyright notices from any part of  SN".
Таким образом первый пункт "дополнения лицензии" противоречит ей.
Второй пункт "доплнения" противоречит духу свободных программ.
https://www.gnu.org/philosophy/selling.html
"Actually, we encourage people who redistribute free software to charge as much as they wish or can. If this seems surprising to you, please read on."
Таким образом на данный момент проект не является свободным с точки зрения GNU GPL и даже не соответсвует этой лицензии.

**Comment by zellfaze** [comment]
I am not a lawyer, but I have read the GPL several times and I though I could add to the discussion.

The GPL already has a clause that does what you want.  According to the GPL people may not remove the copyright notice from the software:

"    a) The work must carry prominent notices stating that you modified it, and giving a relevant date.
    b) The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to 'keep intact all notices'.
    c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.
    d) If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so."

That said, the GPL allows you to require add some requirements to it one of which is:

"b) Requiring preservation of specified reasonable legal notices or author attributions in that material or in the Appropriate Legal Notices displayed by works containing it; or"

So you can require that people preserve legal notices, such as the GPL being mentioned in source files, provided that these requirements are reasonable.  I think in the case of source files, you can easily argue that they are.

You do run into a problem though when you say that they must contact you before selling software.  In your additional terms you mention the following:

"2. You absolutly can not sell SN-based product without my  special  permission.
If you want to sell such product - contact me"

The GPL though states:

"All other non-permissive additional terms are considered 'further restrictions' within the meaning of section 10. If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term. If a license document contains a further restriction but permits relicensing or conveying under this License, you may add to a covered work material governed by the terms of that license document, provided that the further restriction does not survive such relicensing or conveying."

This section of the GPL invalidates your requirement that they contact you for permission before selling SN-based products.

It also states:

"You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License. For example, you may not impose a license fee, royalty, or other charge for exercise of rights granted under this License, and you may not initiate litigation (including a cross-claim or counterclaim in a lawsuit) alleging that any patent claim is infringed by making, using, selling, offering for sale, or importing the Program or any portion of it."

Which makes it a violation of the GPL to add the restriction that you have added.

At least this is my reading of the GPL.  I am not a lawyer.  The GPL was designed around preventing people from breaking the four freedoms.  Your second restriction (that they must get permission to sell derivatives of this software) breaks one of the four freedoms, so it makes sense that the GPL would prevent that.

That said.  I am happy to personally just ignore that restriction and pretend it isn't there.

And please do not take this message the wrong way.  I am of course thankful for the effort that you have put in fixing up the old XNova codebase.  I just wanted to make sure everyone was on the same page legally.

**Comment by supernova-ws** [comment]
Okay. I see the problem. Let’s clarify it.

Version that distributed on GitHub is FULL GPLv2-licensed.

However there is other version of SN which distributed under more strict license. As I can see GPLv2 does not restrict me on releasing same code under different licenses.

Readme.txt belongs to strict-licensed version. It’s somewhat my bad – I missed that point.

I will address this issue in some later releases
