### ISSUE TITLE
after installation, unable to log into admin account

### ISSUE THREAD

**Issue by adamhk0** [supernova-ws/SuperNova#23]
I followed the instruction on install-en to configure the config.php
After everything online, I go to the url, and it show the following.

Происходит обновление сервера - пожалуйста, подождите...
Proishodit obnovlenie servera - pozhalujsta, podozhdute...
Server upgrading now - please wait...
Admin link
Benchmark 0.053210020065308s, memory: 1,890,556

I understand that I have to change password and configure the server. 
When I click the Admin link, It returns this message. 

SuperNova
Игра еще не сконфигурирована

There is no way for me to log into admin account.

Please help.
Thanks.

**Comment by supernova-ws** [comment]
Go to
/login.php
page and login using login/password "admin/admin"

**Comment by adamhk0** [comment]
Hi
Thank for your reply.
I go to /login.php. It redirect me to the page that show the following message

Происходит обновление сервера - пожалуйста, подождите...
Proishodit obnovlenie servera - pozhalujsta, podozhdute...
Server upgrading now - please wait...
Admin link
Benchmark 0.053210020065308s, memory: 1,890,556

**Comment by adamhk0** [comment]
one more thing is I have PHP 5.3.3.
I am not sure if it is the php version causing this issue.
Thank.

**Comment by supernova-ws** [comment]
Something strange happens... 
Okay, let's do this again:
1. Click on "Admin link". It should update game to newest state and redirect you to page with "Игра еще не сконфигурирована" message
2. Navigate to <yourdomain>/login.php - it should bring you login page
3. Use "admin/admin" to login

If it's not helping...
1. Open your SuperNova DB
2. Open config table - most luckely it woud be named "sn_config"
3. Find record "game_disable" - it should be 2 (or may be 1 - if you have problems with your install)
4. Change it from 2 or 1 to 0
5. Save your changes
6. Try instructions above from "Okay, let's do this again"

If this not helps - almost certanly you have missconfigured your game

**Comment by supernova-ws** [comment]
Does this helps?

**Comment by adamhk0** [comment]
Thank for you reply.
It does not work.
The value of "game_disable" is 4. After I changed it to 0, I go to /login.php, it shows
Происходит обновление сервера - пожалуйста, подождите...
Proishodit obnovlenie servera - pozhalujsta, podozhdute...
Server upgrading now - please wait...
Admin link
Benchmark 0.027810096740723s, memory: 1,095,432
when I click on Admin link, it refresh /login.php. It is a loop.
I get my copy of supernova.ws on sourceforge. I did not make any change on the database, I just create a database and import it.

**Comment by adamhk0** [comment]
Okay now. The copy on sourceforge does not work. I re-download it at github, and it works properly.

**Comment by supernova-ws** [comment]
Erm...
Use login: "admin" and password "admin" to log in!

**Comment by adamhk0** [comment]
The same issue is that the initial setting for the value of "game_disable" is 4. It has to be change it to zero manually.

**Comment by adamhk0** [comment]
Thanks a lot.
