### ISSUE TITLE
Не работают настройки option.php

### ISSUE THREAD

**Issue by StrelokSVDAK** [supernova-ws/SuperNova#24]
При нажатии кнопки "[ Настройки ]"   (/index.php?page=options)  выдает только "Benchmark 0.037822008132935s, memory: 3,005,064"      на белом фоне , вряд ли ошибка темплейтов 
Ничего не кастомил , стоковый с гтхаба 

Версия (Project "SuperNova.WS" Release 39 V39d2 © 2009-2015 Gorlum
Inspired by XNova RageRepack v226 ) 

![default](https://cloud.githubusercontent.com/assets/7358326/7946513/b303ed8c-097f-11e5-8a87-e8cf5607924a.png)

**Comment by supernova-ws** [comment]
Что пишет в логе ошибок PHP?
Какая версия PHP установлена?

**Comment by StrelokSVDAK** [comment]
Спасибо , уже решил проблему путем установки файла options с более старого релиза
