### ISSUE TITLE
error

### ISSUE THREAD

**Issue by B1ll1am** [supernova-ws/SuperNova#25]
After getting everything set up this is the error i'm getting.

![capture](https://cloud.githubusercontent.com/assets/12876741/8146103/d3b706e2-11e3-11e5-823c-644a336fc4b6.PNG)

**Comment by supernova-ws** [comment]
What PHP version do you have?

**Comment by supernova-ws** [comment]
SN require PHP > 5.3

**Comment by B1ll1am** [comment]
I am currently using MySQL server version: 5.5.42-37.1
