### ISSUE TITLE
not reload the page automat   "buildings.php?mode=7"

### ISSUE THREAD

**Issue by ogamemaster** [supernova-ws/SuperNova#30]
After finish research Technology the page not reload automat

**Comment by supernova-ws** [comment]
...just as planned. It's not a bug - it's a feature.

**Comment by B1ll1am** [comment]
Yeah I think forcing the players to refresh is a good idea ;)

**Comment by ogamemaster** [comment]
No warning to need reload the page :(

**Comment by B1ll1am** [comment]
I guess you could add it as a tip, I'm not the developer just a guy that likes the server.  I'm only commenting cuz maybe I can help with what I have seen :)

**Comment by supernova-ws** [comment]
It was there but was took away 'cause it's VERY annoying on start levels when you just trying to start-build or start-research (very fast build/research) and page just refresh under your cursor when you want to put smthng in que
And it's pretty useless later in game - when your building/research takes about 10 mins or more. Usually you don't sit 10 minutes looking at one page - you making something else: rebuilding other planet, building fleet, chatting.
So this features by analysis is totally useless.

**Comment by ogamemaster** [comment]
That's actually true

**Comment by supernova-ws** [comment]
Not an issue
