### ISSUE TITLE
Planet starting resources bug

### ISSUE THREAD

**Issue by ogamemaster** [supernova-ws/SuperNova#31]
Default is Metal :500 Crystal :500 Deutrium 
I change the value Metal :5000 Crystal :5000 Deutrium :2000  ----->save
After relogin all change is the default (Default is Metal :500 Crystal :500 Deutrium )

???

**Comment by supernova-ws** [comment]
Looks like your installation is pretty wrong and somehow damaged - you got too much problems that even shouldn't happens.

Revise your system that all components have necessary versions.
Reinstall game from scratch.

**Comment by supernova-ws** [comment]
Installation is damaged
