### ISSUE TITLE
Message to all player not work

### ISSUE THREAD

**Issue by ogamemaster** [supernova-ws/SuperNova#32]
how to fix it?

**Comment by B1ll1am** [comment]
This i cant help with, for me it worked right out of the box.

**Comment by supernova-ws** [comment]
Same here. It should work. Use most recent version from MASTER branch. DO NOT use in production code from TRUNK brunch - unless your specially instructed or fully understands your action,

**Comment by ogamemaster** [comment]
Where is the good php file?

**Comment by B1ll1am** [comment]
As the dev said:
https://github.com/supernova-ws/SuperNova 
and use the master.

Don't give up, the code is solid.

Super awesome game by the way, We have been having a blast!!!

**Comment by ogamemaster** [comment]
I do not see anywhere!and in admin page messall.php not work

**Comment by supernova-ws** [comment]
> Super awesome game by the way, We have been having a blast!!!
Wanna help and translate some locale to English or do a proof-check of already translated strings?

**Comment by ogamemaster** [comment]
please

**Comment by B1ll1am** [comment]
"please"
I would have to agree with the dev start over from scratch and rebuild.

"Wanna help and translate some locale to English or do a proof-check of already translated strings?"
I appreciate the offer, but just don't have the time needed to do any translation work, sorry.

**Comment by supernova-ws** [comment]
> I appreciate the offer, but just don't have the time needed to do any translation work, sorry.
Sure. Not a problem. Worth a try

**Comment by supernova-ws** [comment]
> please

You have severe broken installation. All thing that you post should never happen on normal install.
I'm physically unable to fix remotly every broken installation

**Comment by ogamemaster** [comment]
i have complete translated all english file

**Comment by ogamemaster** [comment]
Work only form news

**Comment by B1ll1am** [comment]
The code is actually really good, I know the dev has been working on this project for a number of years and had it fine tuned by players.  If you're still having issues i would recommend a complete reinstall.

**Comment by supernova-ws** [comment]
6,5+ years now and counting

**Comment by supernova-ws** [comment]
Not a bug
