### ISSUE TITLE
Planet destroyed 

### ISSUE THREAD

**Issue by ogamemaster** [supernova-ws/SuperNova#34]
Planet destroyed  SHOW more time after leaves Colony

**Comment by ogamemaster** [comment]
How to fix itt,to remove automat?

**Comment by B1ll1am** [comment]
wo wo wo hold on here, if i think what you are implying is any indication that a player is on its way to destroy your moon.  This is a strategy game, there absolutely has to be some mystery in the game or what’s the point?

**Comment by supernova-ws** [comment]
Not an issue
