### ISSUE TITLE
Missing Attack indicator in navbar-container!!!!!

### ISSUE THREAD

**Issue by ogamemaster** [supernova-ws/SuperNova#36]
How to add Attack indicator in navbar-container?
Please help

**Comment by B1ll1am** [comment]
Emails should be generating when being probed and attacked, plus there is a sweet icon that shows up  over your planet ;)  Wouldn't an attack indicator in the navbar be overkill?

**Comment by supernova-ws** [comment]
Project discussion & help forum located here: http://forum.supernova.ws/viewforum.php?f=73
GitHub - is not a place for asking help on adding some features
