### ISSUE TITLE
Регистрация

### ISSUE THREAD

**Issue by khivan** [supernova-ws/SuperNova#41]
В последней версии не работает регистрация нового игрока.

**Comment by supernova-ws** [comment]
Странно. Что именно не работает?
Из какой ветки берете инсталляцию? С мастера или с транка?

**Comment by khivan** [comment]
Беру с мастера 
Gorlum LOGIN-fix-42c4: Fixed error creating new planet for new user
вот это и обновляю версию  v41d0 
Вот установка идет под админом захожу норм а вот новый юзер зарегится неможет висит наверно минуты 2 загрузка и на этом все. Но в базе прописывается мыло юзера но ник непрописует в базу.
