### ISSUE TITLE
cant install it

### ISSUE THREAD

**Issue by Goten87** [supernova-ws/SuperNova#42]
its staying in a update loop

> This version does not supports upgrades from SN below v40. Please, use SN v42 to upgrade old database.
Эта версия игры не поддерживает обновление движка версий ниже v40. Пожалуйста, используйте SN v42 для апгрейда со старых версий игры.
Benchmark 0.06034s, memory: 554,736, DB time: 0.055416s

i have tryed stable - nightly build - git clone it all dos the same thing

**Comment by supernova-ws** [comment]
Use login page to login as admin/admin:
/login.php
Then navigate to admin interface
/admin/overview.php

**Comment by Goten87** [comment]
Even the login page is giving me that massage

**Comment by B1ll1am** [comment]
All I can say the game is awesome, support is awesome.  Rock steady programming for sure. Might have to do a complete reinstall.  Did you have a lot of players?

**Comment by Goten87** [comment]
its first install so no players yet

**Comment by Goten87** [comment]
Massage for /login.php
> Происходит обновление сервера - пожалуйста, подождите...
Proishodit obnovlenie servera - pozhalujsta, podozhdute...
Server upgrading now - please wait...
Admin link
Benchmark 0.0050668716430664s, memory: 463,856, DB time: 0.0023441314697266ms

**Comment by supernova-ws** [comment]
Click "Admin link"

**Comment by Goten87** [comment]
yeah then i get the first massage again

**Comment by supernova-ws** [comment]
Check requirements:
PHP 5.6 (not qualified with PHP 7)
MySQL 5.1, 5.3 (need extra configuration of MySQL if version 5.5 or 5.7 - see MySQL error logs)

If not helps - clear browser cookies, reinstall SN from scratch (remove DB)

**Comment by Goten87** [comment]
oke found the issu xD i run php 7.x

**Comment by supernova-ws** [comment]
It should work now in PHP 7 too with some tweaking of php.ini. Check error logs of PHP - there can be some hints how to make it work with SN
PHP 7 would be supported later for sure. However I didn't have ETA for this feature

**Comment by Goten87** [comment]
i only get 1 error in my error.log
`[Sun Jul 23 15:11:53.130493 2017] [access_compat:error] [pid 2003] [client 192.168.178.199:64486] AH01797: client denied by server configuration: /var/www/html/SuperNova/index.html
`

**Comment by supernova-ws** [comment]
Check your environment. It's not an SN error

**Comment by Goten87** [comment]
oke i now have it on my extern webhost and its working how do i chance the admin lang to english ?
and can u make that the new default english for admins

**Comment by supernova-ws** [comment]
Switch language in player options

**Comment by supernova-ws** [comment]
As I understand - you managed to install game. So I close thread

**Comment by Goten87** [comment]
and where is player options ?
sins the `MUST change the administrator password on the page/options.php`
is not existing in the website
