### ISSUE TITLE
Error after installing supernova

### ISSUE THREAD

**Issue by jcageman** [supernova-ws/SuperNova#43]
Hi,

I am receiving the following error when trying to install SuperNova:

`This version does not supports upgrades from SN below v37. Please, use SN v40 to upgrade old database`

I am using the following version of xampp on Windows 10:

Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
PHP extension: mysqli curl mbstring
PHP version: 7.1.9

I already checked the sql and php logs, but those look clean to me. Any specific settings i need to get php 7 working?

**Comment by jcageman** [comment]
I figured it out.. when i enabled the commented out line in update.php:

`//$config->db_loadItem('db_version');`

I now got a correct running environment, is this a bug or related to php 7?

**Comment by jcageman** [comment]
It seems there is a problem loading and saving the configuration. Applying changes in settings.php doesn't work and doesn't apply the results to the database. given the above issue i think there is a general issue with the use of the global settings object.

**Comment by B1ll1am** [comment]
Still using xampp?

**Comment by jcageman** [comment]
Yes, still using xampp

**Comment by supernova-ws** [comment]
Unfortunatly, SN is not certified nor tested for using in PHP 7+ environment. I can't give any recomendation for this environments. Also there can be problems with high versions of MySQL.

If it is possible - please use PHP 5.6 to confirm that problems exists. Looks like there are some incompatibilities in core mechanic of SN (save/load config) with PHP 7+

**Comment by supernova-ws** [comment]
Currently I'm succesfully developing SN on WAMPServer x64 (Windows) with 
Apache 2.4.23
PHP 5.6.25
MySQL 5.7.14

Also it is HIGHLY recommended to use xCache plugin for PHP

**Comment by jcageman** [comment]
I will install WampServer then, thanks for the advise!

**Comment by supernova-ws** [comment]
If you manage to make a succesfull AI-bot - I'd like to get a copy to include it in the game as a part of bot-players.

**Comment by B1ll1am** [comment]
That would be sweet to have some AI players!!!
