### ISSUE TITLE
attacking gets fleet stuck at attacking planet

### ISSUE THREAD

**Issue by jcageman** [supernova-ws/SuperNova#44]
Hi,

All seems to be working fine. Applying settings now works correctly after installing the correct wampserver version.

There is one big issue: whenever i attack another player (same ip) and i send the fleet it goes to the player, but doesn't generate a combat report. It almost looks like the event handling is not taking place. When i try to return the fleet it keeps being in "returning" mode without ever returning. I have game speed on 100 by the way if that would make a difference? Still the travel takes 58 seconds or so, should be nothing problematic.

See the screenshot:
![capture](https://user-images.githubusercontent.com/13038863/31961365-ceec8662-b8fa-11e7-97b1-b6ff70e5d83f.PNG)
![capture](https://user-images.githubusercontent.com/13038863/31961533-43c3a7b8-b8fb-11e7-8322-1d16ebee03fd.PNG)

Its currently 20:35 and the fleet from 20:17 is still returning.. On the players account it also says its returned, but the fleet is not available on the planet.

Thanks!

**Comment by jcageman** [comment]
Somehow the "fleet_update_skip" got set, which caused no updates to be processed, changed it back and now i get battle reports etc.! Probably my own doing at some point.

**Comment by B1ll1am** [comment]
Cool glade you are up and running, have fun!!!

**Comment by supernova-ws** [comment]
Same IP players can't interact - it's by design. Change 
game_multiaccount_enabled
in
`config`
to 
1
and reload config via Admin/Tools menu

**Comment by jcageman** [comment]
Already found that option, thanks for the tip though.
