### ISSUE TITLE
Fatal error: Access to undeclared static property: classSupernova::$design

### ISSUE THREAD

**Issue by ino89** [supernova-ws/SuperNova#47]
hello, I have the latest master version installed and now get the error where can this be located?

Fatal error: Access to undeclared static property: classSupernova::$design in /www/htdocs/w0181031/spaceconflict/includes/functions/sys_bbcode.php on line 3

**Comment by supernova-ws** [comment]
Did you make a fresh install or upgrade old installation?

**Comment by B1ll1am** [comment]
yuppers fresh install does matter
