### ISSUE TITLE
what for PHP Version ?

### ISSUE THREAD

**Issue by agony09** [supernova-ws/SuperNova#50]
Hello, what for PHP Version Need for this script ?
And is "https" possible with this ?

is a german Version aviable ?

**Comment by Langlais115** [comment]
Hy Agony09,

You will need **php 5.6 or higher** to run superNova
For the **https** this is a web server configuration and have nothing to do with this dev.

For the language there is only Russian which is fully supported.
Some English translation have been done but there is still quite some work to be done...

**Comment by agony09** [comment]
ok, thanks a lot
