### ISSUE TITLE
somehow my game cant load correctly

### ISSUE THREAD

**Issue by ratsafalig** [supernova-ws/SuperNova#51]
it just show like this
![1](https://user-images.githubusercontent.com/33503055/54875276-ce6d9780-4e36-11e9-9dc6-12363427a708.png)
and crome shows
![2](https://user-images.githubusercontent.com/33503055/54875279-d6c5d280-4e36-11e9-801e-f2dfade2ce7b.png)
maybe that had something to do with databases?
cause i did change some data in the database

**Comment by ratsafalig** [comment]
well i drop the database and import it again but nothing changed,so it must be something else

**Comment by B1ll1am** [comment]
Dude I love lincoln park, ok let’s see what the issue could be are you hosting out in z cloud or doing some local goodness?

**Comment by ratsafalig** [comment]
thanks and i ve solve it, the problem is because something wrong with my mysql setting
